// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQce6NVMe-dqTv5wp-RHP4KvhQZ6JSF2w',
    appId: '1:527133382185:web:4082811d0b50dfd4796e38',
    messagingSenderId: '527133382185',
    projectId: 'mobilproje-df99d',
    authDomain: 'mobilproje-df99d.firebaseapp.com',
    storageBucket: 'mobilproje-df99d.firebasestorage.app',
    measurementId: 'G-3QFCJHFDW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxZjAmn1MdXXmH_fED043sHJKFqjztuAA',
    appId: '1:527133382185:android:61581cd75f5bd041796e38',
    messagingSenderId: '527133382185',
    projectId: 'mobilproje-df99d',
    storageBucket: 'mobilproje-df99d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAqyWAqHalKXxW9xBQsfb4UYbYlvhwbgQ',
    appId: '1:527133382185:ios:631b67e232884188796e38',
    messagingSenderId: '527133382185',
    projectId: 'mobilproje-df99d',
    storageBucket: 'mobilproje-df99d.firebasestorage.app',
    iosBundleId: 'com.example.btkProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAqyWAqHalKXxW9xBQsfb4UYbYlvhwbgQ',
    appId: '1:527133382185:ios:631b67e232884188796e38',
    messagingSenderId: '527133382185',
    projectId: 'mobilproje-df99d',
    storageBucket: 'mobilproje-df99d.firebasestorage.app',
    iosBundleId: 'com.example.btkProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQce6NVMe-dqTv5wp-RHP4KvhQZ6JSF2w',
    appId: '1:527133382185:web:0484309e054ec67e796e38',
    messagingSenderId: '527133382185',
    projectId: 'mobilproje-df99d',
    authDomain: 'mobilproje-df99d.firebaseapp.com',
    storageBucket: 'mobilproje-df99d.firebasestorage.app',
    measurementId: 'G-7DMR2GZBDJ',
  );
}
